version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get update && apt-get -y install jq
  pre_build:
    commands:
      - printenv
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
      - echo Build completed
  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - aws ecs describe-task-definition --task-definition $ECS_SERVICE_NAME | jq '.taskDefinition' > taskdef.json
      - envsubst < appspec_tpl.yaml > appspec.yaml
artifacts:
  files:
    - taskdef.json
    - appspec.yaml